from enum import Enum

class ShipType(int, Enum):
    NOT_AVAILABLE = 0  # Not available (default)
    RESERVED_1 = 1     # Reserved for future use
    RESERVED_2 = 2
    RESERVED_3 = 3
    RESERVED_4 = 4
    RESERVED_5 = 5
    RESERVED_6 = 6
    RESERVED_7 = 7
    RESERVED_8 = 8
    RESERVED_9 = 9
    RESERVED_10 = 10
    RESERVED_11 = 11
    RESERVED_12 = 12
    RESERVED_13 = 13
    RESERVED_14 = 14
    RESERVED_15 = 15
    RESERVED_16 = 16
    RESERVED_17 = 17
    RESERVED_18 = 18
    RESERVED_19 = 19
    WIG_ALL = 20  # Wing in ground (WIG), all ships of this type
    WIG_HAZARDOUS_A = 21  # Hazardous category A
    WIG_HAZARDOUS_B = 22  # Hazardous category B
    WIG_HAZARDOUS_C = 23  # Hazardous category C
    WIG_HAZARDOUS_D = 24  # Hazardous category D
    WIG_RESERVED_1 = 25  # Reserved for future use
    WIG_RESERVED_2 = 26
    WIG_RESERVED_3 = 27
    WIG_RESERVED_4 = 28
    WIG_RESERVED_5 = 29
    FISHING = 30
    TOWING = 31
    TOWING_LONG = 32  # Towing: length exceeds 200m or breadth exceeds 25m
    DREDGING_OR_UNDERWATER_OPS = 33
    DIVING_OPS = 34
    MILITARY_OPS = 35
    SAILING = 36
    PLEASURE_CRAFT = 37
    RESERVED_38 = 38  # Reserved
    RESERVED_39 = 39  # Reserved
    HSC_ALL = 40  # High speed craft (HSC), all ships of this type
    HSC_HAZARDOUS_A = 41  # Hazardous category A
    HSC_HAZARDOUS_B = 42  # Hazardous category B
    HSC_HAZARDOUS_C = 43  # Hazardous category C
    HSC_HAZARDOUS_D = 44  # Hazardous category D
    HSC_RESERVED_1 = 45  # Reserved for future use
    HSC_RESERVED_2 = 46
    HSC_RESERVED_3 = 47
    HSC_RESERVED_4 = 48
    HSC_NO_ADDITIONAL_INFORMATION = 49
    PILOT_VESSEL = 50
    SEARCH_AND_RESCUE = 51
    TUG = 52
    PORT_TENDER = 53
    ANTI_POLLUTION_EQUIPMENT = 54
    LAW_ENFORCEMENT = 55
    SPARE_LOCAL_VESSEL_1 = 56
    SPARE_LOCAL_VESSEL_2 = 57
    MEDICAL_TRANSPORT = 58
    NONCOMBATANT_SHIP = 59  # Noncombatant ship according to RR Resolution No. 18
    PASSENGER_ALL = 60  # Passenger, all ships of this type
    PASSENGER_HAZARDOUS_A = 61  # Hazardous category A
    PASSENGER_HAZARDOUS_B = 62  # Hazardous category B
    PASSENGER_HAZARDOUS_C = 63  # Hazardous category C
    PASSENGER_HAZARDOUS_D = 64  # Hazardous category D
    PASSENGER_RESERVED_1 = 65  # Reserved for future use
    PASSENGER_RESERVED_2 = 66  # Reserved for future use
    PASSENGER_RESERVED_3 = 67  # Reserved for future use
    PASSENGER_RESERVED_4 = 68  # Reserved for future use
    PASSENGER_NO_ADDITIONAL_INFORMATION = 69
    CARGO_ALL = 70  # Cargo, all ships of this type
    CARGO_HAZARDOUS_A = 71  # Hazardous category A
    CARGO_HAZARDOUS_B = 72  # Hazardous category B
    CARGO_HAZARDOUS_C = 73  # Hazardous category C
    CARGO_HAZARDOUS_D = 74  # Hazardous category D
    CARGO_RESERVED_1 = 75  # Reserved for future use
    CARGO_RESERVED_2 = 76  # Reserved for future use
    CARGO_RESERVED_3 = 77  # Reserved for future use
    CARGO_RESERVED_4 = 78  # Reserved for future use
    CARGO_NO_ADDITIONAL_INFORMATION = 79
    TANKER_ALL = 80  # Tanker, all ships of this type
    TANKER_HAZARDOUS_A = 81  # Hazardous category A
    TANKER_HAZARDOUS_B = 82  # Hazardous category B
    TANKER_HAZARDOUS_C = 83  # Hazardous category C
    TANKER_HAZARDOUS_D = 84  # Hazardous category D
    TANKER_RESERVED_1 = 85  # Reserved for future use
    TANKER_RESERVED_2 = 86  # Reserved for future use
    TANKER_RESERVED_3 = 87  # Reserved for future use
    TANKER_RESERVED_4 = 88  # Reserved for future use
    TANKER_NO_ADDITIONAL_INFORMATION = 89
    OTHER_ALL = 90  # Other Type, all ships of this type
    OTHER_HAZARDOUS_A = 91  # Hazardous category A
    OTHER_HAZARDOUS_B = 92  # Hazardous category B
    OTHER_HAZARDOUS_C = 93  # Hazardous category C
    OTHER_HAZARDOUS_D = 94  # Hazardous category D
    OTHER_RESERVED_1 = 95  # Reserved for future use
    OTHER_RESERVED_2 = 96  # Reserved for future use
    OTHER_RESERVED_3 = 97  # Reserved for future use
    OTHER_RESERVED_4 = 98  # Reserved for future use
    OTHER_NO_ADDITIONAL_INFORMATION = 99
